#! /bin/sh
cd "$(dirname "$0")" || exit 1
source ./common
shutdown
mkdir -p /home/noah/bbts-agent/
mkdir -p /home/noah/bbts-agent/log
#mkdir -p /noah/run/bbts-agent
#cp -rf /home/noah/bbts-agent/resume /noah/run/bbts-agent
exit 0
