/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef announce_CONSTANTS_H
#define announce_CONSTANTS_H

#include "announce_types.h"

namespace bbts { namespace tracker {

class announceConstants {
 public:
  announceConstants();

};

extern const announceConstants g_announce_constants;

}} // namespace

#endif
