/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef inner_CONSTANTS_H
#define inner_CONSTANTS_H

#include "inner_types.h"

namespace bbts { namespace tracker {

class innerConstants {
 public:
  innerConstants();

};

extern const innerConstants g_inner_constants;

}} // namespace

#endif
