/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "inner_constants.h"

namespace bbts { namespace tracker {

const innerConstants g_inner_constants;

innerConstants::innerConstants() {
}

}} // namespace

