/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "tracker_constants.h"

namespace bbts { namespace tracker {

const trackerConstants g_tracker_constants;

trackerConstants::trackerConstants() {
}

}} // namespace

