/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef tracker_CONSTANTS_H
#define tracker_CONSTANTS_H

#include "tracker_types.h"

namespace bbts { namespace tracker {

class trackerConstants {
 public:
  trackerConstants();

};

extern const trackerConstants g_tracker_constants;

}} // namespace

#endif
