/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef GroupService_CONSTANTS_H
#define GroupService_CONSTANTS_H

#include "GroupService_types.h"

namespace bbts { namespace group {

class GroupServiceConstants {
 public:
  GroupServiceConstants();

};

extern const GroupServiceConstants g_GroupService_constants;

}} // namespace

#endif
